const ShopActionTypes = {
    FETCH_COLECTIONS_START: 'FETCH_COLECTIONS_START',
    FETCH_COLECTIONS_SUCCESS: 'FETCH_COLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
}

export default ShopActionTypes;